version: "3.8"
services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./project:/var/www/html
      - ./nginx:/etc/nginx/conf.d
      - ./php:/usr/local/etc/php/conf.d
      - ./php-fpm:/usr/local/etc/php-fpm.d
      - ./supervisor:/etc/supervisor/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./logs/php:/var/log/php
      - ./logs/supervisor/:/var/log/supervisor
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]
      interval: 2s
      timeout: 3s
      retries: 3
      start_period: 40s
    depends_on:
      - mysql-server
      - redis-server
    networks:
      - backend
      - frontend
    ports:
      - '80:80'
  redis-server:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - ./redis:/usr/local/etc/redis
    networks:
      - backend
    depends_on:
      - mysql-server
  mysql-server:
    image: mysql:5.7
    ports:
      - '3306:3306'
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping","-h","localhost" ]
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
      - ./logs/mysql:/data/mysql/logs
      - ./mysql/conf:/etc/mysql/conf.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --explicit_defaults_for_timestamp=true
      - --innodb-use-native-aio=0
      - --default-authentication-plugin=mysql_native_password
      - --max_connections=1000
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_db_root
    secrets:
      - mysql_db_root
    networks:
      - backend
  adminer-server:
    image: adminer:latest
    restart: always
    depends_on:
      - mysql-server
    healthcheck:
      test: [ "CMD", "php", "-r", "echo file_get_contents('http://localhost:8080');" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - '8089:8080'
    networks:
      - backend
networks:
  backend:
  frontend:
secrets:
  mysql_db_root:
    file: ./mysql/mysqlroot.txt
